name: Update Collection.json

on:
  workflow_dispatch:
  schedule: ## Schedule the job to run at 12.am daily.
  - cron: '0 12 * * *'

jobs:
  mainjob1:
    runs-on: macos-13
    # strategy:
    #   matrix:
    #     swift: ["5.9"]
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      # - uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: '15.0'
      # - name: Build ReposDumper    
      #   run: |
      #     cd ReposDumper
      #     swift build -c release --disable-sandbox --arch arm64 --arch x86_64
      #     cd ..
      #     cp -rf ReposDumper/.build/apple/Products/Release/ReposDumper DumperCLI

      - name: Run ReposDump
        run: swift run -c release --package-path ReposDumper
      
      - name: package-collection-generate
        run: |
          git clone --branch 5.9 https://github.com/apple/swift-package-collection-generator
          cd swift-package-collection-generator
          swift run package-collection-generate ../input.json ../kivy_packages.json --auth-token github:github.com:${{ secrets.SPM_TOKEN }}
          #mv unsigned-collection.json ../kivy_packages.json
      - name: list dir
        run: ls
      
      - uses: actions/upload-artifact@v4
        with:
          name: collection-output
          path: ./kivy_packages.json
  
  uploadJSON:
    runs-on: ubuntu-latest
    needs: [mainjob1]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/download-artifact@v3
        with:
          name: collection-output

      # - name: Pushes to another repository
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.SPM_TOKEN }}
      #   with:
      #     source-directory: './'
      #     destination-github-username: 'kivyswiftpackages'
      #     destination-repository-name: 'packages'
      #     user-email: pythonswiftlink@gmail.com
      #     target-branch: main

     
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.SPM_TOKEN }}
